[package]
name = "bank"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "1.14.6"
grasscrete = {path = "grasscrete"}
getrandom = { version = "0.2.2", features = ["custom"] }

[lib]
name = "bank"
crate-type = ["cdylib", "lib"]
